name: Backend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  ECR_REPO: movie-picture-backend-repo
  EKS_CLUSTER_NAME: movie-picture-backend-cluster
  PYTHON_VERSION: "3.9"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      # - name: Install dependencies
      #   run: |
      #     cd starter/backend
      #     echo "All good"
      #     python -m pip install --upgrade pipenv
      #     pipenv install
      # - name: flake8 Lint
      #   uses: py-actions/flake8@v2
  # test:
  #   runs-on: ubuntu-latest
  #   steps:

  # build:
  #   needs: [linter, test]
  #   runs-on: ubuntu-latest
  #   steps:
